import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await page.getByRole('button', { name: /Preview Momentum/i }).click()
  await expect(page.getByRole('heading', { name: /Tayah/ })).toBeVisible()
})

test('keeps Today focused and free of horizontal overflow', async ({ page }) => {
  await expect(page.getByRole('progressbar')).toBeVisible()
  await expect(page.locator('.exercise-card').first()).toBeVisible()
  await expect(page.locator('.today-view .primary-button:visible')).toHaveCount(1)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)

  const nav = page.getByRole('navigation', { name: 'Main navigation' })
  const box = await nav.boundingBox()
  expect(box?.y).toBeLessThanOrEqual((await page.evaluate(() => window.innerHeight)) - 50)
  await expect(nav.getByRole('button')).toHaveCount(4)
  expect(await page.locator('.app-frame').evaluate((element) => parseFloat(getComputedStyle(element).paddingTop))).toBeGreaterThanOrEqual(12)
})

test('centers the completion check and clears the in-app notification badge', async ({ page }) => {
  const completion = page.locator('.exercise-card').filter({ hasText: 'Goblet squat' }).locator('.check-button')
  await expect(completion).toHaveAccessibleName(/Mark Goblet squat complete/)
  await completion.click()
  const buttonBox = await completion.boundingBox()
  const checkBox = await completion.locator('svg').boundingBox()
  expect(Math.abs((buttonBox!.x + buttonBox!.width / 2) - (checkBox!.x + checkBox!.width / 2))).toBeLessThan(1)
  expect(Math.abs((buttonBox!.y + buttonBox!.height / 2) - (checkBox!.y + checkBox!.height / 2))).toBeLessThan(1)

  const bell = page.getByRole('button', { name: /Open notifications, 1 unread/ })
  await expect(bell).toBeVisible()
  await bell.click()
  await expect(page.getByRole('dialog', { name: 'Notifications' })).toBeVisible()
  await expect(page.locator('.notification-badge')).toHaveCount(0)
  await page.getByRole('tab', { name: /Reminders/ }).click()
  await expect(page.getByText(/of 3 exercises complete/)).toBeVisible()
  await page.getByRole('button', { name: 'Close notifications' }).click()
  await expect(page.getByRole('button', { name: 'Open notifications', exact: true })).toBeVisible()
})

test('keeps friends, challenges, profile, and policies calm inside More', async ({ page }) => {
  await page.getByRole('button', { name: 'More', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'A little more.' })).toBeVisible()
  await expect(page.getByRole('button', { name: /Friends/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /Challenges/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /Workout reminders/ })).toHaveCount(0)
  await expect(page.getByRole('button', { name: /Health|Samsung|watch/i })).toHaveCount(0)

  await page.getByRole('button', { name: /Friends/ }).click()
  await expect(page.getByRole('heading', { name: 'Friends', exact: true })).toBeVisible()
  await expect(page.getByText('Exact matches only.')).toBeVisible()
  await expect(page.getByText('Your workout journal stays private.')).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('heading', { name: 'A little more.' })).toBeVisible()

  await page.getByRole('button', { name: /Profile & timezone/ }).click()
  await expect(page.getByRole('dialog', { name: 'Your profile' })).toBeVisible()
  await page.getByLabel('Display name').fill('Tayah M')
  await expect(page.getByText('Unsaved changes')).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('alertdialog', { name: 'Discard profile changes?' })).toBeVisible()
  await page.getByRole('button', { name: 'Discard' }).click()

  await page.getByRole('button', { name: /Privacy policy/ }).click()
  await expect(page.getByRole('heading', { name: 'What Momentum stores' })).toBeVisible()
  await expect(page.getByText(/does not connect to Samsung Health/)).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('makes policies available before sign-in', async ({ page }) => {
  await page.evaluate(() => sessionStorage.removeItem('momentum-demo-active'))
  await page.goto('/?legal=terms')
  await expect(page.getByRole('heading', { name: 'Terms of use' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Fitness, not medical advice' })).toBeVisible()
  await page.getByRole('button', { name: 'Back to Momentum' }).click()
  await expect(page.getByRole('heading', { name: 'Welcome back' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Privacy policy' })).toBeVisible()
})

test('unwinds picker, dirty editor, and selected day with Android Back', async ({ page }) => {
  await page.getByRole('button', { name: /Edit today’s workout/i }).click()
  await expect(page).toHaveURL(/date=\d{4}-\d{2}-\d{2}/)
  await page.getByRole('button', { name: 'Add exercise' }).click()
  await expect(page.getByRole('dialog', { name: 'Add an exercise' })).toBeVisible()

  await page.goBack()
  await expect(page.getByRole('dialog', { name: 'Add an exercise' })).toBeHidden()
  await expect(page.getByRole('button', { name: 'Save changes' })).toBeVisible()

  const title = page.getByPlaceholder('Full body reset')
  await title.fill('A focused session')
  await expect(page.getByText('Unsaved changes')).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('alertdialog', { name: 'Discard your changes?' })).toBeVisible()
  await page.getByRole('button', { name: 'Keep editing' }).click()
  await expect(page.getByRole('button', { name: 'Save changes' })).toBeVisible()

  await page.goBack()
  await page.getByRole('button', { name: 'Discard' }).click()
  await expect(page.getByRole('heading', { name: /Tayah/ })).toBeVisible()
})

test('keeps calendar and library usable at Android viewports', async ({ page }) => {
  await page.getByRole('button', { name: 'Calendar' }).click()
  await expect(page.getByRole('heading', { name: /2026|2027|2028|2029|2030/ })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)

  await page.getByRole('button', { name: 'Library' }).click()
  await expect(page.getByRole('heading', { name: 'The library.' })).toBeVisible()
  await expect(page.locator('.library-card')).toHaveCount(24)
  await page.getByRole('searchbox', { name: 'Search exercises' }).fill('plank')
  await expect(page.locator('.library-card')).toHaveCount(1)
  await page.getByRole('searchbox', { name: 'Search exercises' }).fill('upper body')
  await expect(page.locator('.library-card').first()).toBeVisible()
  expect(await page.locator('.library-card').count()).toBeGreaterThan(1)
  await expect(page.locator('.library-card .focus-tag')).toHaveText([/Upper body/, /Upper body/, /Upper body/, /Upper body/, /Upper body/, /Upper body/])

  await page.getByRole('button', { name: 'Create custom exercise' }).click()
  await page.getByRole('button', { name: 'Category' }).click()
  await expect(page.getByRole('dialog', { name: 'Choose a category' })).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('dialog', { name: 'Choose a category' })).toBeHidden()
  await expect(page.getByRole('dialog', { name: 'Create an exercise' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('lets the user remove any library exercise without changing saved workout history', async ({ page }) => {
  await page.getByRole('button', { name: 'Library', exact: true }).click()
  await expect(page.locator('.library-card')).toHaveCount(24)
  await page.getByRole('button', { name: 'Remove Goblet squat from library' }).click()
  await expect(page.getByRole('alertdialog', { name: 'Remove Goblet squat?' })).toBeVisible()
  await page.getByRole('button', { name: 'Remove exercise' }).click()
  await expect(page.locator('.library-card')).toHaveCount(23)
  await expect(page.getByRole('button', { name: 'Edit Goblet squat' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Today', exact: true }).click()
  await expect(page.locator('.exercise-card').filter({ hasText: 'Goblet squat' })).toBeVisible()
})

test('saves personal reps and weight, reloads them, and snapshots them only into new additions', async ({ page }) => {
  const originalTargets = await page.locator('.exercise-card .exercise-copy > span').allTextContents()
  await page.getByRole('button', { name: 'Library', exact: true }).click()
  await page.getByRole('button', { name: 'Edit Goblet squat', exact: true }).click()
  await page.getByLabel('Sets & reps').fill('4 × 8')
  await page.getByLabel('Weight optional').fill('22.5')
  await page.getByRole('button', { name: 'kg', exact: true }).click()
  await expect(page.getByText('Unsaved changes')).toBeVisible()
  await page.getByRole('button', { name: 'Save changes' }).click()
  await expect(page.getByRole('status')).toHaveText('Saved')
  await page.getByRole('button', { name: 'Back to library' }).click()
  await expect(page.getByRole('heading', { name: 'The library.' })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Edit Goblet squat', exact: true }).click()
  await expect(page.getByLabel('Sets & reps')).toHaveValue('4 × 8')
  await expect(page.getByLabel('Weight optional')).toHaveValue('22.5')
  await expect(page.getByRole('button', { name: 'kg', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Back to library' }).click()
  await page.getByRole('button', { name: 'Today', exact: true }).click()
  await expect(page.locator('.exercise-card .exercise-copy > span')).toHaveText(originalTargets)
  await page.getByRole('button', { name: 'Edit today’s workout' }).click()
  await page.getByRole('button', { name: 'Add exercise', exact: true }).click()
  await page.getByRole('button', { name: /Goblet squat/ }).click()
  await expect(page.getByRole('textbox', { name: 'Target for Goblet squat', exact: true }).last()).toHaveValue('4 × 8 · 22.5 kg')
  await page.getByRole('button', { name: 'Save changes' }).click()
  await expect(page.getByRole('button', { name: 'Edit workout', exact: true })).toBeVisible()
})

test('guards exercise edits on Android Back and supports optional settings', async ({ page }) => {
  await page.getByRole('button', { name: 'Library', exact: true }).click()
  await page.getByRole('button', { name: 'Edit Goblet squat', exact: true }).click()
  await page.getByLabel('Sets & reps').fill('5 × 5')
  await page.goBack()
  await expect(page.getByRole('alertdialog', { name: 'Discard your changes?' })).toBeVisible()
  await page.getByRole('button', { name: 'Keep editing' }).click()
  await expect(page.getByLabel('Sets & reps')).toHaveValue('5 × 5')
  await page.goBack()
  await page.getByRole('button', { name: 'Discard', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'The library.' })).toBeVisible()
  await page.getByRole('button', { name: 'Edit Goblet squat', exact: true }).click()
  await expect(page.getByLabel('Sets & reps')).not.toHaveValue('5 × 5')
  await page.getByLabel('Sets & reps').fill('')
  await page.getByLabel('Weight optional').fill('')
  await page.getByRole('button', { name: 'Save changes' }).click()
  await expect(page.getByRole('status')).toHaveText('Saved')
})

test('keeps the exercise editor reachable in a short viewport and read-only offline', async ({ page, context }) => {
  await page.getByRole('button', { name: 'Library', exact: true }).click()
  await page.getByRole('button', { name: 'Edit Goblet squat', exact: true }).click()
  await page.setViewportSize({ width: 360, height: 390 })
  await page.getByLabel('Weight optional').fill('15')
  const save = page.getByRole('button', { name: 'Save changes' })
  await expect(save).toBeInViewport()
  await expect(page.getByLabel('Weight optional')).toBeInViewport()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await context.setOffline(true)
  await expect(save).toBeDisabled()
  await expect(page.getByLabel('Sets & reps')).toBeDisabled()
  await context.setOffline(false)
  await expect(save).toBeEnabled()
})
